AkerlyLaw/Controllers/FormController.cs
using AkerlyLaw.Models;
using MailKit.Security;
using System;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using MimeKit;
using MimeKit.Text;
using AkerlyLaw.Helpers;
using Microsoft.Extensions.Configuration;
using AkerlyLaw.DBModels;

namespace AkerlyLaw.Controllers
{
    public class FormController : Controller
    {

        private IConfiguration configuration;

        private CopperheadContext _context;


        public FormController(IConfiguration iConfig, CopperheadContext context)
        {
            configuration = iConfig;
            _context = context;
        }

        public IActionResult GetPartial(string id)
        {
            ContactFormModel model = new ContactFormModel() {
                Page = id 
            };

            return PartialView("_ContactForm", model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<IActionResult> Contact(ContactFormModel Contact)
        {
            string secret = configuration.GetSection("GoogleReCaptcha").GetSection("secret").Value;

            if (!await GoogleRecaptchaHeler.IsReCaptchaPassedAsync(Request.Form["g-recaptcha-response"], secret))
            {
                //error
                //ModelState.AddModelError(string.Empty, "You failed the CAPTCHA");
                //return View(model);
                RedirectToAction("Index", "Home");
            }
            SaveLead(Contact);
            Sendmail(Contact);

            return RedirectToAction("Confirmation");
        }

        public IActionResult Confirmation(ContactFormModel Contact)
        {

            return View();
        }

        public void Sendmail(ContactFormModel Contact)
        {
            var messageToSend = new MimeMessage();

            messageToSend.From.Add(new MailboxAddress("website-lead-no-reply", "akerly.law.lead@gmail.com"));
            messageToSend.To.Add(new MailboxAddress("Akerly-Info", "info@akerlylaw.com"));
            messageToSend.To.Add(new MailboxAddress("Shelly", "sakerly@akerlylaw.com"));
            messageToSend.To.Add(new MailboxAddress("Michael-Test", "msvajhart@outlook.com"));
            //messageToSend.To.Add(new MailboxAddress("leadbox2", "michael.svajhart@okstate.edu"));
            messageToSend.Subject = "Form Completed By: " + Contact.Name;

            StringBuilder sb = new StringBuilder();
            sb.AppendFormat("Name: {0}", Contact.Name);
            sb.AppendLine();
            if (Contact.Page != null)
            {
                sb.AppendFormat("Page Details: {0}", Contact.Page);
                sb.AppendLine();
            }
            sb.AppendFormat("Email: {0}", Contact.Email);
            sb.AppendLine();
            sb.AppendFormat("Phone: {0}", Contact.Phone);
            sb.AppendLine();
            sb.AppendFormat("Company: {0}", Contact.Company);
            sb.AppendLine();
            sb.AppendFormat("Address: {0} {1} {2} {3} {4}", Contact.Address, Contact.City, Contact.State, Contact.Zip, Contact.Country);
            sb.AppendLine();
            sb.AppendLine("Information:");
            sb.AppendFormat("{0}", Contact.Description);


            messageToSend.Body = new TextPart(TextFormat.Plain) { Text = sb.ToString() };

            using (var smtp = new MailKit.Net.Smtp.SmtpClient())
            {
                smtp.Connect("smtp.gmail.com", 587);
                smtp.Authenticate("akerly.law.lead@gmail.com", "ihuevgyaeklepwjx");
                try
                {
                    smtp.Send(messageToSend);
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Exception caught in CreateTestMessage2(): {0}",
                          ex.ToString());
                }

                smtp.Disconnect(true);
            }

        }


        public void SaveLead(ContactFormModel Contact)
        {
            Leads lead = new Leads
            {
                WebsiteID = 1,
                Name = Contact.Name,
                Email = Contact.Email,
                Phone = Contact.Phone,
                Company = Contact.Company,
                Address = Contact.Address,
                City = Contact.City,
                State = Contact.State,
                ZipCode = Contact.Zip,
                Country = Contact.Country,
                Comments = Contact.Description
            };

            _context.Leads.Add(lead);
            _context.SaveChanges();
        }

        public void SendContactEmail(ContactFormModel Contact){

            Leads lead = new Leads
            {
                WebsiteID = 1,
                Name = Contact.Name,
                Email = Contact.Email,
                Phone = Contact.Phone,
                Company = Contact.Company,
                Address = Contact.Address,
                City = Contact.City,
                State = Contact.State,
                ZipCode = Contact.Zip,
                Country = Contact.Country,
                Comments = Contact.Description
            };

            _context.Leads.Add(lead);
            _context.SaveChanges();

            /*var messageToSend = new MimeMessage();

            messageToSend.From.Add(new MailboxAddress("website-lead-no-reply", "akerly.law.lead@gmail.com"));
            //messageToSend.To.Add(new MailboxAddress("leadbox", "info@akerlylaw.com"));
            //messageToSend.To.Add(new MailboxAddress("leadbox", "sakerly@akerlylaw.com"));
            messageToSend.To.Add(new MailboxAddress("leadbox1", "msvajhart@outlook.com"));
            //messageToSend.To.Add(new MailboxAddress("leadbox2", "michael.svajhart@okstate.edu"));
            messageToSend.Subject = "Form Completed By: " + Contact.Name;

            StringBuilder sb = new StringBuilder();
            sb.AppendFormat("Name: {0}", Contact.Name);
            sb.AppendLine();
            if (Contact.Page != null)
            {
                sb.AppendFormat("Page Details: {0}", Contact.Page);
                sb.AppendLine();
            }
            sb.AppendFormat("Email: {0}", Contact.Email);
            sb.AppendLine();
            sb.AppendFormat("Phone: {0}", Contact.Phone);
            sb.AppendLine();
            sb.AppendFormat("Company: {0}", Contact.Company);
            sb.AppendLine();
            sb.AppendFormat("Address: {0} {1} {2} {3} {4}", Contact.Address, Contact.City, Contact.State, Contact.Zip, Contact.Country);
            sb.AppendLine();
            sb.AppendLine("Information:");
            sb.AppendFormat("{0}", Contact.Description);


            messageToSend.Body = new TextPart(TextFormat.Plain) { Text = sb.ToString() };

            using (var smtp = new MailKit.Net.Smtp.SmtpClient())
            {
                smtp.Connect("smtp.gmail.com", 587);
                smtp.Authenticate("akerly.law.lead@gmail.com", "Xeruses115");
                try
                {
                    smtp.Send(messageToSend);
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Exception caught in CreateTestMessage2(): {0}",
                          ex.ToString());
                }
                
                smtp.Disconnect(true);
            }*/
            
        }

    }
}

AkerlyLaw/Controllers/LawController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AkerlyLaw.Helpers;
using AkerlyLaw.DBModels;
using AkerlyLaw.Models;

namespace AkerlyLaw.Controllers
{
    public class LawController : Controller
    {

        private readonly CopperheadContext _context;

        public LawController(CopperheadContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            FirmModel model = LawHelper.GetLaw(_context);

            return View(model);
        }

        public IActionResult Details(string id)
        {
            LawModel Law = LawHelper.GetLawDetails(_context, id);
            LawChildren Children = LawHelper.GetLawChildren(_context, id);
            LawModel before = LawHelper.GetLawDetailsBefore(_context, id); ;
            LawModel after = LawHelper.GetLawDetailsAfter(_context, id); ;
            LawDetailsViewModel model = new LawDetailsViewModel(Law, Children, before, after);

            if (model == null)
            {
                RedirectToAction("Index");
            }

            return View(model);
        }
    }
}

AkerlyLaw/Views/Shared/_ContactForm.cshtml
@model AkerlyLaw.Models.ContactFormModel;
@inject Microsoft.Extensions.Configuration.IConfiguration _config;
<script src='https://www.google.com/recaptcha/api.js'></script>
<section id="contact">
    <div class="container contact__container contact__form">
        <h2 class="form__title">We want to hear from you.</h2>
        <p class="form__disclaimer">Please feel free to fill out the form below and we will ensure it is directed to the right person.   Please note that completing a form or sending an email does not establish an attorney-client relationship.</p>
        <form class="fancy__form color__white" asp-controller="Form" asp-action="Contact">
            <input asp-for="Page" hidden id="contact__page__details" />
            <div class="form__row">
                <input asp-for="Name" required />
                <label asp-for="Name"></label>
                <div class="after"></div>
            </div>
            <div class="form__group">
                <div class="form__row">
                    <input asp-for="Email" required />
                    <label asp-for="Email"></label>
                    <div class="after"></div>
                </div>


                <div class="form__row">
                    <input asp-for="Phone" required />
                    <label asp-for="Phone"></label>
                    <div class="after"></div>
                </div>
            </div>
            <div class="form__group">
                <div class="form__row">
                    <input asp-for="Company" required />
                    <label asp-for="Company"></label>
                    <div class="after"></div>
                </div>

                <div class="form__row">
                    <input asp-for="Address" required />
                    <label asp-for="Address"></label>
                    <div class="after"></div>
                </div>
            </div>
            <div class="form__group">
                <div class="form__row">
                    <input asp-for="City" required />
                    <label asp-for="City"></label>
                    <div class="after"></div>
                </div>

                <div class="form__row">
                    <input asp-for="State" required />
                    <label asp-for="State"></label>
                    <div class="after"></div>
                </div>
            </div>


            <div class="form__group">
                <div class="form__row">
                    <input asp-for="Zip" required />
                    <label asp-for="Zip"></label>
                    <div class="after"></div>
                </div>

                <div class="form__row">
                    <input asp-for="Country" required />
                    <label asp-for="Country"></label>
                    <div class="after"></div>
                </div>
            </div>



            <div class="form__row">
                <textarea asp-for="Description" required></textarea>
                <label asp-for="Description"></label>
                <div class="after"></div>
            </div>
            <div class="form__row">
                <div class="g-recaptcha" data-sitekey="@_config["GoogleReCaptcha:key"]"></div>
            </div>
            <div class="footer__form__row last">
                <button>Submit</button>
            </div>
        </form>
    </div>
</section>
<script type="text/javascript">
    function initReCaptcha() {
        console.log("firing")
        var $recaptcha = document.querySelector('#g-recaptcha-response');
        if ($recaptcha) {
            $recaptcha.setAttribute("required", "required");
        };
    }

    initReCaptcha();
</script>
<style>
    .form__group{
        display:flex;
        flex-direction:column;
        width:100%;
        justify-content:space-between;
    }

    .form__group .form__row{
        width:100%
    }

    .form__title{
        display:block;
        width:100%;
        text-align:center;
        padding:0;
        color:#e54a35;
        font-size:2.25rem;
        margin: 0 0 .75rem;
    }
    .form__disclaimer{
        display:block;
        font-size:1.125rem;
        letter-spacing:1px;
        line-height:1.2;
        color:#fff;
        margin: 0 auto 2rem;
        width:100%;
        max-width:600px;
        text-align:justify;
    }

    @@media (min-width:768px) {
        .form__group{
            flex-direction:row;
        }

        .form__group .form__row{
            width:48%;
        }
    }



    #g-recaptcha-response {
        display: block !important;
        position: absolute;
        margin: -78px 0 0 0 !important;
        width: 302px !important;
        height: 76px !important;
        z-index: -999999;
        opacity: 0;
    }
    @@media (max-width:360px){
        .g-recaptcha {
            transform: scale(.6);
        }
    }
    
</style>

AkerlyLaw/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Akerly Law</title>
    <meta name="description" content="@ViewData["Description"]" />
    <meta name="keywords" content="Akerly Law, Texas Law Firm, North Dallas Law, Coppel Law, Super Lawyer, Construction Law,  Bankruptcy Law, Dallas Law, Fort Worth Law, DFW Law Firm, Bankruptcy Law, Agricultural and Food Safety Claim, Preferential or Fraudulent Transfers, Shareholder and Partnership Disputes, Business Workouts and Restructures, Creditors Rights, Business Litigation" />
    <meta name="robots" content="index,follow" />

    <meta property="og:title" content="@ViewData["Title"] | Akerly Law" />
    <meta property="og:description" content="@ViewData["Description"]" />
    <meta property="og:image" content="//www.akerlylaw.com/img/logo.png" />
    <meta property="og:url" content="https://www.akerlylaw.com">

    <script type="application/ld+json">
        {
        "@@context": "https://schema.org",
        "@@type": "LegalService",
        "@@id": "https://www.akerlylaw.com",
        "name": "Akerly Law",
        "address": {
        "@@type": "PostalAddress",
        "streetAddress": "878 S Denton Tap Rd Suite 100",
        "addressLocality": "Coppell",
        "addressRegion": "TX",
        "postalCode": "75019",
        "addressCountry": "US"
        },
        "url": "https://www.akerlylaw.com/",
        "telephone": "4694441878",
        "openingHoursSpecification": [
        {
        "@@type": "OpeningHoursSpecification",
        "dayOfWeek": [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday"
        ],
        "opens": "9:00",
        "closes": "17:00"
        }
        ],
        "image": "//www.akerlylaw.com/img/logo.png",
        "priceRange": "$$"
        }
    </script>
    <script type="application/ld+json">
        {
        "@@context": "https://schema.org",
        "@@type": "WebSite",
        "name": "Akerly Law",
        "url": "https://www.akerlylaw.com/ ",
        "image": "//www.akerlylaw.com/img/logo.png"
        }
    </script>

    <!--<meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@@nytimes">
    <meta name="twitter:creator" content="@@SarahMaslinNir">
    <meta name="twitter:title" content="Parade of Fans for Houston’s Funeral">
    <meta name="twitter:description" content="NEWARK - The guest list and parade of limousines with celebrities emerging from them seemed more suited to a red carpet event in Hollywood or New York than than a gritty stretch of Sussex Avenue near the former site of the James M. Baxter Terrace public housing project here.">
    <meta name="twitter:image" content="~/img/">-->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-145842489-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-145842489-1');
    </script>
    <link href="https://fonts.googleapis.com/css?family=Tinos:400,700&display=swap" rel="stylesheet">
    <!--<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700&display=swap" rel="stylesheet">-->
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/focuspoint/css/focuspoint.css" />
        <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
        <link rel="stylesheet" href="~/lib/animate/animate.css" />
        <link rel="stylesheet" href="~/lib/slick-1.8.1/slick/slick-theme.css" />
        <link rel="stylesheet" href="~/lib/slick-1.8.1/slick/slick.css" />
        <link rel="stylesheet" href="~/css/site.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/focuspoint/css/focuspoint.css" />
        <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" />
        <link rel="stylesheet" href="~/lib/animate/animate.min.css" />
        <link rel="stylesheet" href="~/lib/slick-1.8.1/slick/slick-theme.css" />
        <link rel="stylesheet" href="~/lib/slick-1.8.1/slick/slick.css" />
        <link rel="stylesheet" href="~/css/site.min.css" />
    </environment>
</head>
<body>
    <partial name="_CookieConsentPartial" />
    <header>
        <div class="nav__button color_primary">
            <i class="fas fa-bars"></i>
            <i class="fas fa-times"></i>
        </div>
        <nav itemscope itemtype="https://schema.org/SiteNavigationElement">
            <a class="nav__logo" asp-controller="Home" asp-action="Index">
                <img src="~/img/logo.png" />
            </a>
            <div class="nav__list">
                <a class="nav__item" asp-controller="Home" asp-action="Index" itemprop="url"><span itemprop="name">Home</span></a>
                <div class="nav__dropdown__container nav__item" >
                    <span class="dropdown__title">Our Firm <i class="fas fa-chevron-down"></i></span>
                    <div class="nav__dropdown">
                        <a class="nav__item" asp-controller="Law" asp-action="Index" itemprop="url"><span itemprop="name">About Us</span></a>
                        <a class="nav__item" asp-controller="Law" asp-action="Details" asp-route-id="Business-Law" itemprop="url"><span itemprop="name">Business Law</span></a>
                        <a class="nav__item" asp-controller="Law" asp-action="Details" asp-route-id="Business-Litigation" itemprop="url"><span itemprop="name">Business Litigation</span></a>
                        <a class="nav__item" asp-controller="Law" asp-action="Details" asp-route-id="Bankruptcy-And-Restructuring" itemprop="url"><span itemprop="name">Bankruptcy and Restructuring</span></a>
                        <a class="nav__item" asp-controller="Law" asp-action="Details" asp-route-id="Agricultural-Law" itemprop="url"><span itemprop="name">Agricultural Law</span></a>
                        <a class="nav__item" asp-controller="Law" asp-action="Details" asp-route-id="Appeals" itemprop="url"><span itemprop="name">Appeals</span></a>
                        <a class="nav__item" asp-controller="Law" asp-action="Details" asp-route-id="Collection-Law" itemprop="url"><span itemprop="name">Collection Law</span></a>
                        <a class="nav__item" asp-controller="Law" asp-action="Details" asp-route-id="Construction-Law" itemprop="url"><span itemprop="name">Construction Law</span></a>
                    </div>
                </div>
                <a class="nav__item" asp-controller="Team" asp-action="Index" itemprop="url"><span itemprop="name">Our Team</span></a>
                <a class="nav__item" asp-controller="News" asp-action="Index" itemprop="url"><span itemprop="name">News &amp; Resources</span></a>
                <a class="nav__item" asp-controller="Home" asp-action="Contact" itemprop="url"><span itemprop="name">Contact Us</span></a>
            </div>
        </nav>

    </header>
    <div class="nav__padding"></div>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer class="footer">
        <div class="footer__container">
            <div class="footer__col footer__left">
                <div calss="footer__copy">&copy; @DateTime.Now.Year | Akerly Law | <a style="display:inline-block" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></div>
            </div>
            <div class="footer__col footer__right">
                <div class="footer__phone">
                    <a href="tel:469-444-1878"><i class="fas fa-phone"></i> (469) 444-1878</a><br /><br />
                    <p><i class="fas fa-fax"></i> (469) 444-1801</p>
                </div>
                <div class="social__links">
                    <a href="https://www.linkedin.com/company/akerly-law-pllc" target="_blank"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <div class="footer__map">
                    <a class="address" href="https://www.google.com/maps/place/Akerly+Law,+PLLC/@@32.9490087,-96.9949199,17z/data=!3m1!4b1!4m5!3m4!1s0x864c29c969c255f3:0x48041ccecc7ec3ec!8m2!3d32.9490042!4d-96.9927312">
                        878 S. Denton Tap Rd.<br />
                        Suite 100<br />
                        Coppell, TX 75019<br />
                    </a>
                </div>
            </div>

        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/focuspoint/js/focuspoint.js"></script>
        <script src="~/lib/slick-1.8.1/slick/slick.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="~/lib/focuspoint/js/focuspoint.min.js"
                asp-fallback-src="~/lib/focuspoint/js/focuspoint.js">
        </script>
        <script src="~/lib/slick-1.8.1/slick/slick.min.js"
                asp-fallback-src="~/lib/slick-1.8.1/slick/slick.js">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>